# Generated by Django 4.2.14 on 2024-09-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='default_images/user-logo.png', null=True, upload_to='testimonials/'),
        ),
    ]
