# Generated by Django 4.2.14 on 2025-01-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(upload_to='clients/'),
        ),
    ]
